version: "3.8"

services:
  trash-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trash-server
    ports:
      - "5000:5000"
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - SITE_AUTH_USER=${SITE_AUTH_USER}
      - SITE_AUTH_PASS=${SITE_AUTH_PASS}
    volumes:
      - ./src/data:/app/src/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:5000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - trash-network

networks:
  trash-network:
    driver: bridge
